AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

